#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESH_Desafio6.DomainModel.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Desafio6db")]
	public partial class DdDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAluno(Aluno instance);
    partial void UpdateAluno(Aluno instance);
    partial void DeleteAluno(Aluno instance);
    #endregion
		
		public DdDataContext() : 
				base(global::ESH_Desafio6.DomainModel.Properties.Settings.Default.Desafio6dbConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DdDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DdDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DdDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DdDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Aluno> Aluno
		{
			get
			{
				return this.GetTable<Aluno>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alunos")]
	public partial class Aluno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NomeCompleto;
		
		private System.DateTime _DataNascimento;
		
		private string _RA;
		
		private int _TurmaId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomeCompletoChanging(string value);
    partial void OnNomeCompletoChanged();
    partial void OnDataNascimentoChanging(System.DateTime value);
    partial void OnDataNascimentoChanged();
    partial void OnRAChanging(string value);
    partial void OnRAChanged();
    partial void OnTurmaIdChanging(int value);
    partial void OnTurmaIdChanged();
    #endregion
		
		public Aluno()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeCompleto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomeCompleto
		{
			get
			{
				return this._NomeCompleto;
			}
			set
			{
				if ((this._NomeCompleto != value))
				{
					this.OnNomeCompletoChanging(value);
					this.SendPropertyChanging();
					this._NomeCompleto = value;
					this.SendPropertyChanged("NomeCompleto");
					this.OnNomeCompletoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascimento", DbType="Date NOT NULL")]
		public System.DateTime DataNascimento
		{
			get
			{
				return this._DataNascimento;
			}
			set
			{
				if ((this._DataNascimento != value))
				{
					this.OnDataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DataNascimento = value;
					this.SendPropertyChanged("DataNascimento");
					this.OnDataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RA", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string RA
		{
			get
			{
				return this._RA;
			}
			set
			{
				if ((this._RA != value))
				{
					this.OnRAChanging(value);
					this.SendPropertyChanging();
					this._RA = value;
					this.SendPropertyChanged("RA");
					this.OnRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TurmaId", DbType="Int NOT NULL")]
		public int TurmaId
		{
			get
			{
				return this._TurmaId;
			}
			set
			{
				if ((this._TurmaId != value))
				{
					this.OnTurmaIdChanging(value);
					this.SendPropertyChanging();
					this._TurmaId = value;
					this.SendPropertyChanged("TurmaId");
					this.OnTurmaIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
